---
abstract: 'VIC is a high level syntax to generate PIC microcontroller assembly'
author:
  - 'Vikas N. Kumar <vikas@cpan.org>'
build_requires:
  File::Spec: 0
  Module::Build: 0
  Pegex: 0.55
  Test::More: 0
  bareword::filehandles: 0
  indirect: 0
  multidimensional: 0
  strictures: 0
configure_requires:
  Module::Build: 0
  Software::License: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4207, CPAN::Meta::Converter version 2.132661'
keywords:
  - VIC
  - PIC
  - assembly
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VIC
no_index:
  directory:
    - t
  namespace:
    - VIC::PIC::Roles
    - VIC::PIC::Functions
provides:
  VIC:
    file: lib/VIC.pm
    version: 0.14
  VIC::Command:
    file: lib/VIC/Command.pm
    version: 0.14
  VIC::Grammar:
    file: lib/VIC/Grammar.pm
    version: 0.14
  VIC::PIC::Any:
    file: lib/VIC/PIC/Any.pm
    version: 0.14
  VIC::PIC::Base:
    file: lib/VIC/PIC/Base.pm
    version: 0.14
  VIC::PIC::Functions::ADC:
    file: lib/VIC/PIC/Functions/ADC.pm
  VIC::PIC::Functions::CCP:
    file: lib/VIC/PIC/Functions/CCP.pm
  VIC::PIC::Functions::Chip:
    file: lib/VIC/PIC/Functions/Chip.pm
  VIC::PIC::Functions::CodeGen:
    file: lib/VIC/PIC/Functions/CodeGen.pm
  VIC::PIC::Functions::Comparator:
    file: lib/VIC/PIC/Functions/Comparator.pm
  VIC::PIC::Functions::ECCP:
    file: lib/VIC/PIC/Functions/ECCP.pm
  VIC::PIC::Functions::GPIO:
    file: lib/VIC/PIC/Functions/GPIO.pm
  VIC::PIC::Functions::I2C:
    file: lib/VIC/PIC/Functions/I2C.pm
  VIC::PIC::Functions::ISR:
    file: lib/VIC/PIC/Functions/ISR.pm
  VIC::PIC::Functions::Operations:
    file: lib/VIC/PIC/Functions/Operations.pm
  VIC::PIC::Functions::Operators:
    file: lib/VIC/PIC/Functions/Operators.pm
  VIC::PIC::Functions::PSP:
    file: lib/VIC/PIC/Functions/PSP.pm
  VIC::PIC::Functions::SPI:
    file: lib/VIC/PIC/Functions/SPI.pm
  VIC::PIC::Functions::SRLatch:
    file: lib/VIC/PIC/Functions/SRLatch.pm
  VIC::PIC::Functions::Timer:
    file: lib/VIC/PIC/Functions/Timer.pm
  VIC::PIC::Functions::USART:
    file: lib/VIC/PIC/Functions/USART.pm
  VIC::PIC::Functions::USB:
    file: lib/VIC/PIC/Functions/USB.pm
  VIC::PIC::Gpsim:
    file: lib/VIC/PIC/Gpsim.pm
    version: 0.14
  VIC::PIC::P12F683:
    file: lib/VIC/PIC/P12F683.pm
    version: 0.14
  VIC::PIC::P16F627A:
    file: lib/VIC/PIC/P16F627A.pm
    version: 0.14
  VIC::PIC::P16F628A:
    file: lib/VIC/PIC/P16F628A.pm
    version: 0.14
  VIC::PIC::P16F631:
    file: lib/VIC/PIC/P16F631.pm
    version: 0.14
  VIC::PIC::P16F648A:
    file: lib/VIC/PIC/P16F648A.pm
    version: 0.14
  VIC::PIC::P16F677:
    file: lib/VIC/PIC/P16F677.pm
    version: 0.14
  VIC::PIC::P16F685:
    file: lib/VIC/PIC/P16F685.pm
    version: 0.14
  VIC::PIC::P16F687:
    file: lib/VIC/PIC/P16F687.pm
    version: 0.14
  VIC::PIC::P16F689:
    file: lib/VIC/PIC/P16F689.pm
    version: 0.14
  VIC::PIC::P16F690:
    file: lib/VIC/PIC/P16F690.pm
    version: 0.14
  VIC::PIC::P18F13K50:
    file: lib/VIC/PIC/P18F13K50.pm
    version: 0.14
  VIC::PIC::P18F14K50:
    file: lib/VIC/PIC/P18F14K50.pm
    version: 0.14
  VIC::PIC::P18F242:
    file: lib/VIC/PIC/P18F242.pm
    version: 0.14
  VIC::PIC::P18F252:
    file: lib/VIC/PIC/P18F252.pm
    version: 0.14
  VIC::PIC::P18F442:
    file: lib/VIC/PIC/P18F442.pm
    version: 0.14
  VIC::PIC::P18F452:
    file: lib/VIC/PIC/P18F452.pm
    version: 0.14
  VIC::PIC::P18LF13K50:
    file: lib/VIC/PIC/P18LF13K50.pm
    version: 0.14
  VIC::PIC::P18LF14K50:
    file: lib/VIC/PIC/P18LF14K50.pm
    version: 0.14
  VIC::PIC::Roles::ADC:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::CCP:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::Chip:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::CodeGen:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::Comparator:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::ECCP:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::GPIO:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::I2C:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::ISR:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::Operations:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::Operators:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::PSP:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::SPI:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::SRLatch:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::Timer:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::USART:
    file: lib/VIC/PIC/Roles.pm
  VIC::PIC::Roles::USB:
    file: lib/VIC/PIC/Roles.pm
  VIC::Parser:
    file: lib/VIC/Parser.pm
    version: 0.14
  VIC::Receiver:
    file: lib/VIC/Receiver.pm
    version: 0.14
recommends:
  App::Prove: 0
  XXX: 0
requires:
  File::ShareDir: 1.00
  File::Spec: 0
  Getopt::Long: 0
  List::MoreUtils: 0
  List::Util: 0
  Moo: 0
  Pegex: 0.55
  namespace::clean: 0
resources:
  IRC: irc://irc.freenode.net/#vic
  Twitter: https://twitter.com/_vicash_
  bugtracker: https://github.com/selectiveintellect/vic/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/selectiveintellect/vic
version: 0.14
